---
- hosts: client
  gather_facts: yes
  become: yes

  tasks:
    - name: Backup Teleport binary
      ansible.builtin.shell: sudo mv /usr/local/bin/teleport /usr/local/bin/teleport.bak

    - name: Copy TeleportV11 tarball 
      copy:
        src: /tmp/playbooks/teleport-v11.3.2-linux-amd64-bin.tar.gz
        dest: /tmp/v11
    
    - name: Extract the Teleport tarball
      ansible.builtin.unarchive:
        src: /tmp/v11/teleport-v11.3.2-linux-amd64-bin.tar.gz
        dest: /tmp/v11
        remote_src: yes

    - name: Install Teleport
      ansible.builtin.shell: /tmp/v11/teleport/./install

        # - name: Fork a new Teleport process
        #ansible.builtin.shell: sudo kill -USR2 $(pidof teleport)
    
      

